import { getSupabase, INTAKE_TABLE, isSupabaseConfigured } from './supabaseClient';
import { IntakeCase, IntakeData, IntakeScore, IntakeStatus } from '../types';
import { getFirmId } from './caseStore';

// ── Resolve a public intake token → firm_id ──────────────────────────────────
// Tokens are now PER-CLIENT (e.g. "1x2c1") generated by the attorney per prospect.
// Falls back to firm-level token lookup for backwards compatibility.
// Returns firm_id so the submission is always tagged to the correct firm.
export const resolveFirmToken = async (token: string): Promise<string | null> => {
  const supabase = getSupabase();
  if (!supabase || !token) return null;

  // 1. Try client_invites first (new model)
  const { data: invite } = await supabase
    .from('client_invites')
    .select('firm_id')
    .eq('token', token)
    .maybeSingle();
  if (invite?.firm_id) return invite.firm_id;

  // 2. Fall back to firm-level token (old model / plain firm links)
  const { data: firm } = await supabase
    .from('firm_memberships')
    .select('firm_id')
    .eq('intake_token', token)
    .maybeSingle();
  return firm?.firm_id ?? null;
};

// ── Get or generate the current firm's intake token ─────────────────────────
// Called from the attorney's Intake Inbox to display/copy their shareable link.
export const getOrCreateIntakeToken = async (): Promise<string | null> => {
  const supabase = getSupabase();
  if (!supabase) return null;
  const { data: { session } } = await supabase.auth.getSession();
  if (!session?.user) return null;
  const userId = session.user.id;

  // Try to fetch existing token
  const { data } = await supabase
    .from('firm_memberships')
    .select('intake_token, firm_id')
    .eq('user_id', userId)
    .maybeSingle();

  if (data?.intake_token) return data.intake_token as string;

  // No token yet — generate and save one
  const chars = 'abcdefghijkmnpqrstuvwxyz23456789';
  let t = '';
  const arr = new Uint8Array(10);
  crypto.getRandomValues(arr);
  arr.forEach(b => { t += chars[b % chars.length]; });

  await supabase
    .from('firm_memberships')
    .update({ intake_token: t })
    .eq('user_id', userId);

  return t;
};

// Persists intake cases to Supabase so a prospect's submission on their own
// device shows up live in the attorney's dashboard. Falls back to localStorage
// (single-device) when Supabase isn't reachable, so the flow never hard-fails.

const LOCAL_KEY = 'casebuddy_intake_cases';
const RETRY_QUEUE_KEY = 'casebuddy_intake_retry_queue';

// ── Retry Queue ─────────────────────────────────────────────────────────────
// When Supabase insert fails, stash the row here. On next page load (or when
// connectivity returns), retry all queued intakes.

const loadRetryQueue = (): IntakeCase[] => {
  try { return JSON.parse(localStorage.getItem(RETRY_QUEUE_KEY) || '[]'); } catch { return []; }
};

const saveRetryQueue = (rows: IntakeCase[]) => {
  try { localStorage.setItem(RETRY_QUEUE_KEY, JSON.stringify(rows.slice(0, 50))); } catch { /* full */ }
};

/** Flush any queued-for-retry intakes to Supabase. Call on app init. */
export const flushRetryQueue = async (): Promise<number> => {
  const supabase = getSupabase();
  if (!supabase) return 0;
  const queue = loadRetryQueue();
  if (queue.length === 0) return 0;

  let flushed = 0;
  const remaining: IntakeCase[] = [];

  for (const row of queue) {
    const { error } = await supabase.from(INTAKE_TABLE).upsert(row, { onConflict: 'id' });
    if (error) {
      remaining.push(row);
    } else {
      flushed++;
    }
  }

  saveRetryQueue(remaining);
  if (flushed > 0) console.info(`[intakeStore] Flushed ${flushed} queued intakes to Supabase`);
  return flushed;
};

const dispositionToStatus = (d: IntakeScore['disposition']): IntakeStatus =>
  d === 'accepted' ? 'routed' : d === 'denied' ? 'denied' : 'new';

const loadLocal = (): IntakeCase[] => {
  try {
    return JSON.parse(localStorage.getItem(LOCAL_KEY) || '[]');
  } catch {
    return [];
  }
};

const saveLocal = (rows: IntakeCase[]) => {
  try {
    localStorage.setItem(LOCAL_KEY, JSON.stringify(rows.slice(0, 200)));
  } catch {
    /* storage full — ignore */
  }
};

export interface SubmitIntakeArgs {
  intake: IntakeData;
  score: IntakeScore;
  transcript: { speaker: string; text: string }[];
  /** firm_id resolved from the public intake token — required for multi-tenant isolation */
  firmId?: string;
  /** client_invite_id — ties this submission back to the specific client invite */
  clientInviteId?: string;
}

/** Build a row from the extracted intake + score. */
const buildRow = ({ intake, score, transcript, firmId, clientInviteId }: SubmitIntakeArgs): IntakeCase => ({
  id: (globalThis.crypto?.randomUUID?.() ?? `intake_${Date.now()}_${Math.random().toString(36).slice(2)}`),
  created_at: new Date().toISOString(),
  // firm_id scopes the intake to this firm's dashboard (migration 0005).
  // VITE_FIRM_ID is the canonical firm ID for this deployment; falls back to
  // the device's localStorage UUID so single-user installs still work.
  // Use VITE_FIRM_ID when set (Vercel env var); otherwise fall back to 'default'
  // so intakes from anonymous/public devices are always visible on the dashboard.
  // Previously fell back to getFirmId() which generated a random UUID per device,
  // causing intakes from prospects to be invisible to the attorney.
  // Priority order:
  //   1. firmId from token URL param (multi-tenant — another firm's branded link)
  //   2. VITE_FIRM_ID env var        (owner's generic casebuddy.live/intake link)
  //   3. getFirmId() localStorage    (local-only / dev fallback)
  // This ensures casebuddy.live/intake ALWAYS routes to the owner's dashboard.
  firm_id: firmId || (import.meta.env.VITE_FIRM_ID as string | undefined) || getFirmId(),
  full_name: intake.fullName,
  contact: intake.contact,
  matter_type: intake.matterType,
  jurisdiction: intake.jurisdiction,
  summary: intake.summary,
  score: score.score,
  disposition: score.disposition,
  status: dispositionToStatus(score.disposition),
  recommended_department: score.recommendedDepartment,
  recommended_agent_id: score.recommendedAgentId,
  urgency: score.urgency,
  client_invite_id: clientInviteId || undefined,
  intake,
  score_detail: score,
  transcript,
});

/** Save a completed, scored intake. Returns the stored row. */
export const submitIntake = async (args: SubmitIntakeArgs): Promise<IntakeCase> => {
  const row = buildRow(args);  // firmId passed through SubmitIntakeArgs
  const supabase = getSupabase();

  if (supabase) {
    const { data, error } = await supabase.from(INTAKE_TABLE).insert(row).select().single();
    if (!error && data) {
      // Mirror locally so the originating device has an offline copy too.
      saveLocal([data as IntakeCase, ...loadLocal().filter(r => r.id !== row.id)]);
      return data as IntakeCase;
    }
    // Fall through to local on RLS/table/network errors so intake never blocks.
    // eslint-disable-next-line no-console
    console.warn('[intakeStore] Supabase insert failed, queuing for retry:', error?.message);
    // Queue for retry on next app load / connectivity change
    saveRetryQueue([row, ...loadRetryQueue()]);
  }

  saveLocal([row, ...loadLocal()]);
  return row;
};

/** Fetch all intake cases (most recent first). */
export const fetchIntakes = async (): Promise<IntakeCase[]> => {
  const supabase = getSupabase();
  if (supabase) {
    // RLS already scopes to firm — but we also filter explicitly for defence-in-depth
    const firmId = getFirmId();
    const { data, error } = await supabase
      .from(INTAKE_TABLE)
      .select('*')
      .eq('firm_id', firmId)
      .order('created_at', { ascending: false })
      .limit(200);
    if (!error && data) {
      saveLocal(data as IntakeCase[]);
      return data as IntakeCase[];
    }
    if (error) console.warn('[intakeStore] fetchIntakes error:', error.message);
  }
  return loadLocal();
};

/** Update an intake's workflow status (accept / deny / route from the inbox). */
export const updateIntakeStatus = async (id: string, status: IntakeStatus): Promise<void> => {
  const supabase = getSupabase();
  if (supabase) {
    await supabase.from(INTAKE_TABLE).update({ status }).eq('id', id);
  }
  saveLocal(loadLocal().map(r => (r.id === id ? { ...r, status } : r)));
};

/**
 * Subscribe to live intake inserts. Calls `onInsert` whenever a new intake is
 * created (e.g. a prospect finishing a voice intake on another device).
 * Returns an unsubscribe function.
 */
export const subscribeIntakes = (onInsert: (row: IntakeCase) => void): (() => void) => {
  const supabase = getSupabase();
  if (!supabase) return () => {};

  const channel = supabase
    .channel('intake_cases_feed')
    .on(
      'postgres_changes',
      { event: 'INSERT', schema: 'public', table: INTAKE_TABLE },
      payload => onInsert(payload.new as IntakeCase)
    )
    .subscribe();

  return () => {
    supabase.removeChannel(channel);
  };
};

export const intakeBackendLabel = isSupabaseConfigured
  ? 'Live · synced across devices'
  : 'Local only · this device';
